# Time the player wakes to; Default set to normal time
wake-time: 23450

# Delay before sleeping starts; 200 ticks = 10 seconds
sleep-delay: 200

# Message when sleeping
sleeping-msg: is now sleeping.